db:
  image: postgres:9.4
cache:
  image: redis:3.0.5
web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - .:/app
  links:
    - db
    - cache
  environment:
    - PYTHONDONTWRITEBYTECODE=1
    - DATABASE_URL=postgres://postgres@db/postgres
    - REDIS_URL=redis://cache:6379
    - DEBUG=True
    - ALLOWED_HOSTS=localhost,127.0.0.1,
    - SECRET_KEY=59114b6a-2858-4caf-8878-482a24ee9542
  command:
    ./bin/run-dev.sh
